// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountShares(ctx context.Context) (int64, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	ListShares(ctx context.Context) ([]Share, error)
}

var _ Querier = (*Queries)(nil)
